[package]
name = "elgamal-with-sharing"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"

[dependencies]
# Public dependencies (present in public API of the crate).
curve25519-dalek = "3.1.0"
rand_core = "0.5"

# Private dependencies (not exposed via public APIs).
byteorder = "1.4.3"
merlin = "3.0.0"
smallvec = "1.6.1"
subtle = "2.4.0"

[dev-dependencies]
criterion = "0.3.4"
hex = "0.4.3"
rand = "0.7"
rand_chacha = "0.2"

[[bench]]
name = "basics"
path = "benches/basics.rs"
harness = false

[[bench]]
name = "sharing"
path = "benches/sharing.rs"
harness = false
